# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'afn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'AFNetworking'
  use_frameworks!

  # Pods for afn

  target 'afnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'afnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
